AWSTemplateFormatVersion: '2010-09-09'
Description: Phase 3 - Create only an S3 bucket for testing

Resources:
  ReceiptsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub receipts-app-bucket-${AWS::AccountId}-${AWS::Region}
      AccessControl: Private

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref ReceiptsS3Bucket

